{{- if and (eq .Values.installMode "host") (eq .Values.certs.mode "auto") }}
{{- $name := include "karmada.name" . -}}
{{- $namespace := include "karmada.namespace" . -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ $name }}-post-delete"
  namespace: {{ $namespace }}
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    {{- include "karmada.postDeleteJob.labels" . | nindent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": {{ .Values.postDeleteJob.hookDeletePolicy }}
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: {{ $name }}
      labels:
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      {{- include "karmada.imagePullSecrets" . | nindent 6 }}
      {{- with .Values.postDeleteJob.tolerations}}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.postDeleteJob.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ $name }}-hook-job
      restartPolicy: Never
      containers:
        - name: post-delete
          image: {{ template "karmada.kubectl.image" . }}
          imagePullPolicy: {{ .Values.kubectl.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - |
              bash <<'EOF'
              set -ex
              kubectl delete -f /opt/mount/ --ignore-not-found=true
              kubectl delete -n {{ $namespace }} --ignore-not-found=true \
                cm/{{ $name }}-crds-kustomization \
                cm/{{ $name }}-crds-apps-bases \
                cm/{{ $name }}-crds-autoscaling-bases \
                cm/{{ $name }}-crds-config-bases \
                cm/{{ $name }}-crds-multicluster-bases \
                cm/{{ $name }}-crds-networking-bases \
                cm/{{ $name }}-crds-policy-bases \
                cm/{{ $name }}-crds-remedy-bases \
                cm/{{ $name }}-crds-work-bases \
                cm/{{ $name }}-config
              kubectl delete deployment/{{ $name }}-controller-manager -n {{ $namespace }} --ignore-not-found=true
              EOF
          volumeMounts:
            - name: mount
              mountPath: /opt/mount
      volumes:
      - name: mount
        configMap:
          name: {{ $name }}-config
{{- end }}
